version: "3"
services:
  mysql8.0:
    image: mysql:8.0
    container_name: MYSQLINVEST8.0
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=network_chat
      - MYSQL_USER=alisancho
      - MYSQL_PASSWORD=frfw4f434r3f44g
      - MYSQL_ROOT_PASSWORD=joolpass684523rw3eq3e
#      - TZ=${TIMEZONE}
#    volumes:
#      - ./my.cnf:/root/.my.cnf:ro
#      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
#      - ./mysql8.0/logs:/var/log/mysql:rw
#      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
#      - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
#      - ./auto-generate:/auto-generate:rw